final infoMessages = {
  "required": "This field is required",
  "validatePassword": "Password not contain special character",
  "comfirmPassword": "Please comfirm password",
};

final genderChoice = [
  "Female",
  "Male",
];

final userApi = {
  "id": 1,
  "avatar": "assets/images/avatar.jpg",
  "banner": "assets/images/banner.jpg",
  "username": "Pandoraloveth",
  "first_name": "chioma",
  "last_name": "ifebunso",
  "email": "pandoraloveth17@gmail.com",
  "phone_number": "+2349018398960",
  "additional_phone_number": "",
  "birthday": "2022-01-01",
  "gender": "female",
  "university": "benson idahosa university",
  "state": "Edo",
  "city": "benin city",
};

const university = [
  "Abia State University",
  "Abubakar Tafawa Balewa University",
  "Achievers University",
  "Adamawa State University",
  "Adekunle Ajasin University",
  "Adeleke University",
  "Admiralty University of Nigeria",
  "Afe Babalola University",
  "African University of Science and Technology",
  "Ahmadu Bello University",
  "Ajayi Crowther University",
  "Akwa Ibom State University",
  "Alex Ekwueme Federal University",
  "Al-Hikmah University",
  "Al-Qalam University",
  "Ambrose Alli University",
  "American University of Nigeria",
  "Anchor University",
  "Arthur Jarvis University",
  "Atiba University",
  "Augustine University",
  "Babcock University",
  "Bauchi State University",
  "Bayero University",
  "Baze University",
  "Bells University of Technology",
  "Benson Idahosa University",
  "Benue State University",
  "Bingham University",
  "Borno State University",
  "Bowen University",
  "Caleb University",
  "Caritas University",
  "Chrisland University",
  "Christopher University",
  "Chukwuemeka Odumegwu Ojukwu University",
  "Clifford University",
  "Coal City University",
  "Covenant University",
  "Crawford University",
  "Crescent University",
  "Cross River University of Technology",
  "Crown Hill University",
  "Delta State University",
  "Dominican University",
  "Eastern Palm University",
  "Ebonyi State University",
  "Edo University",
  "Edwin Clark University",
  "Ekiti State University",
  "Eko University of Medical and Health Sciences",
  "Elizade University",
  "Enugu State University of Science and Technology",
  "Federal University of Agriculture, Abeokuta	Abeokuta",
  "Federal University of Petroleum Resources Effurun",
  "Federal University of Technology Akure",
  "Federal University of Technology Minna",
  "Federal University of Technology Owerri",
  "Federal University Birnin Kebbi",
  "Federal University Dutse",
  "Federal University Dutsin-Ma",
  "Federal University Gashua",
  "Federal University Gusau",
  "Federal University Kashere",
  "Federal University Lafia",
  "Federal University Lokoja",
  "Federal University Otuoke",
  "Federal University Oye-Ekiti",
  "Federal University Wukari",
  "Fountain University Osogbo",
  "Glorious Vision University",
  "Godfrey Okoye University",
  "Gombe State University",
  "Gombe State University of Science and Technology",
  "Gregory University",
  "Hallmark University",
  "Hezekiah University",
  "Ibrahim Badamasi Babangida University",
  "Igbinedion University Okada",
  "Ignatius Ajuru University of Education",
  "Imo State University",
  "Joseph Ayo Babalola University",
  "Kaduna State University",
  "Kano University of Science and Technology",
  "Kebbi State University of Science and Technology",
  "Kings University",
  "Kogi State University",
  "Kola Daisi University",
  "Kwara State University",
  "Kwararafa University",
  "Ladoke Akintola University of Technology",
  "Lagos State University",
  "Landmark University",
  "Lead City University",
  "Legacy University",
  "Madonna University",
  "Mcpherson University",
  "Michael and Cecilia Ibru University",
  "Michael Okpara University of Agriculture",
  "Modibbo Adama University of Technology",
  "Moshood Abiola University of Science and Technology",
  "Mountain Top University",
  "Nasarawa State University",
  "Niger Delta University	Wilberforce Island",
  "Nigerian Maritime University",
  "Nile University of Nigeria",
  "Nnamdi Azikiwe University",
  "Novena University",
  "Obafemi Awolowo University",
  "Obong University",
  "Oduduwa University",
  "Olabisi Onabanjo University",
  "Ondo State University of Science and Technology",
  "Osun State University",
  "PAMO University of Medical Sciences	Port-Harcourt",
  "Pan-Atlantic University",
  "Paul University",
  "Plateau State University",
  "Precious Cornerstone University",
  "Redeemer's University",
  "Renaissance University",
  "Rhema University",
  "Ritman University",
  "Rivers State University",
  "Salem University",
  "Skyline University Nigeria",
  "Sokoto State University",
  "Southwestern University",
  "Spiritan University",
  "Sule Lamido University",
  "Summit University",
  "Tai Solarin University of Education",
  "Tansian University",
  "Taraba State University",
  "The Technical University Ibadan",
  "Umaru Musa Yar'Adua University",
  "University of Abuja",
  "University of Africa Toru-Orua",
  "University of Agriculture Makurdi",
  "University of Benin",
  "University of Calabar",
  "University of Ibadan",
  "University of Ilorin",
  "University of Jos",
  "University of Lagos",
  "University of Maiduguri",
  "University of Medical Sciences Ondo City",
  "University of Nigeria Nsukka",
  "University of Port Harcourt",
  "University of Uyo",
  "Usmanu Danfodio University Sokoto",
  "Veritas University",
  "Wellspring University",
  "Wesley University of Science and Technology",
  "Western Delta University",
  "Yobe State University",
  "Yusuf Maitama Sule University Kano",
  "Zamfara State University",
];

final addressBookApi = [
  {
    "id": 1,
    "first_name": "Chioma",
    "last_name": "Ifebunso",
    "address": "No: 14 bole street yola YOLA-CENTRAL LOCATIONS, Adamawa",
    "phone_number": "+2349018398960",
    "additional_phone_number": "+2347039330833",
    "is_primary": true,
  },
  {
    "id": 2,
    "first_name": "Ibukunoluwa",
    "last_name": "Naphtali",
    "address": "No 33 Adeyi Street, Old bodija IBADAN-BODIJA, Oyo",
    "phone_number": "+2349018398960",
    "additional_phone_number": "+2348120051529",
    "is_primary": false,
  },
];

final pendingRatingApi = [
  {
    "id": 1,
    "image": "assets/images/seller6.jpg",
    "product_name": "Plan Polo T-shirt",
    "product_discription":
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam tincidunt magna et vehicula placerat. Aenean lacus nisi, aliquam sit amet neque eu, elementum tempus arcu. Vivamus congue rhoncus diam. Nam lectus nisl.",
    "bought_on": "2021-10-28",
  },
  {
    "id": 2,
    "image": "assets/images/seller2.jpg",
    "product_name": "Men gray english suit",
    "product_discription":
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam tincidunt magna et vehicula placerat. Aenean lacus nisi, aliquam sit amet neque eu, elementum tempus arcu. Vivamus congue rhoncus diam. Nam lectus nisl.",
    "bought_on": "2022-01-08",
  },
];

final recentSearchApi = [
  {
    "id": 1,
    "search_query": "Dell 5510 Charger",
  },
  {
    "id": 2,
    "search_query": "Office Chair",
  },
  {
    "id": 3,
    "search_query": "iPhone 11 Case",
  },
  {
    "id": 4,
    "search_query": "Plan Polo T-shirt",
  },
];
